SELECT empno, ename, sal FROM emp WHERE deptno = 10;
SELECT ename, hiredate, deptno FROM emp WHERE empno = 7369;
SELECT * FROM emp WHERE ename = 'ALLEN';
SELECT ename, deptno, sal FROM emp WHERE hiredate = '1981-05-01';
SELECT * FROM emp WHERE job = 'MANAGER';
SELECT * FROM emp WHERE hiredate = '81-04-02';
SELECT ename, sal, deptno FROM emp WHERE sal >=800;
SELECT * FROM emp WHERE deptno >= 20;
SELECT ename FROM emp WHERE ename >= 'K';
 SELECT ename, sal, deptno FROM emp WHERE hiredate >= '1981-04-02' AND hiredate <= '1982-12-09';
 SELECT empno, ename FROM emp WHERE empno <= 7698;
 SELECT empno, ename FROM emp WHERE empno < 7654 OR empno > 7782;
SELECT ename FROM emp WHERE ename >= 'B' AND ename <= 'J';
SELECT hiredate, ename FROM emp WHERE hiredate < '1981-01-01' OR hiredate > '1981-12-31';
SELECT ename, job FROM emp WHERE job IN('MANAGER', 'SALESMAN');
SELECT ename, empno, deptno FROM emp WHERE deptno NOT IN ('20', '30');
SELECT empno, ename, hiredate, deptno FROM emp WHERE ename LIKE 'S%';
SELECT hiredate, ename FROM emp WHERE hiredate LIKE '1981%';
SELECT ename, sal, comm, sal+comm FROM emp WHERE comm IS NOT NULL ORDER BY 4 DESC;
SELECT ename, sal, sal*1.13 AS bonus, deptno FROM emp;
SELECT ename, deptno, sal, sal*13.5 AS 연봉 FROM emp WHERE deptno = 30;
SELECT ename, sal, ROUND(sal/60) AS 시급 FROM emp WHERE deptno = 20;
SELECT ename, sal, sal*0.15 AS 회비 FROM emp WHERE sal BETWEEN 1500 AND 3000;
SELECT ename, sal, sal*0.15 As 경조비 FROM emp WHERE sal >= 2000;
SELECT ename, sal, sal*0.9 AS 실수령액 FROM emp ORDER BY 2 DESC;